#!/usr/bin/env perl
use strict;
use warnings;
use utf8;
use 5.010;
use Data::Dumper;
use Mojo::URL;
use WWW::Flatten;
use Getopt::Long 'GetOptionsFromArray';
use Pod::Usage;
use Data::Dumper;

my %options;
my $bot = WWW::Flatten->new(basedir => './output/');

GetOptionsFromArray(\@ARGV, \%options,
    'basedir|b=s' => sub {
        $bot->basedir($_[1])
    },
    'depth|d=i' => sub {
        $bot->depth($_[1]); warn $_[1];
    },
    'max_retry|r=i' => sub {
        $bot->max_retry($_[1])
    },
    'max_conn|c=i' => sub {
        $bot->max_conn_per_host($_[1])
    },
    'max_conn_per_host|ch=i' => sub {
        $bot->max_conn_per_host($_[1])
    },
    'cookie|ck=s' => sub {
        my $cookies = Mojo::Cookie::Response->parse($_[1]);
        $bot->ua->cookie_jar(Mojo::UserAgent::CookieJar->new->add(@$cookies));
    },
    'help|?' => sub {
        pod2usage(1); exit;
    },
    "version|v" => sub {
        say 'WWW::Flatten v'. $WWW::Flatten::VERSION; exit;
    },
) or pod2usage(-verbose => 1);

-d $bot->basedir || mkdir($bot->basedir) || die 'basedir is not writable';

$bot->filenames->{pop @ARGV} = 'index.html';
$bot->is_target(sub {
    my ($job, $context) = @_;
    return ((ref $context) ne 'Mojo::DOM' || $context->type !~ qr{^(form|a)$});
});
$bot->on(start => sub {
    shift->say_start;
});

$bot->crawl;

=head1 NAME

wwwflatten - Command line interface to WWW::Flatten

=head1 SYNOPSIS

wwwflatten [options] <starting URL>

=head1 OPTIONS

    -b, --basedir   : output directory defalts to ./output
    -d, --depth     : max depth to crawl defaults to 10
    -r, --max_retry : max re-try in case server is in-responsible defaults to 3
    -c, --max_conn  : max connection defaults to 1
    -ch, --max_conn_per_host : max connection per host defaults to 1
    -ck, --cookie   : set cookie for every requests
    -v, --version   : print the version of dancer being used
    -h, --help      : print what you are currently reading

=head1 DESCRIPTION

WWW-Flatten flattens web pages recursively with assets.
This crawling covers not only single page but also beyond the links.

=head1 EXAMPLE

    wwwflatten http://github.com/
    wwwflatten -d=2 -c=4 http://github.com/

=head1 SEE ALSO

=cut
